export const ACCIONES_PERMISO = [
  'ver_todo',
  'editar_planillas',
  'eliminar_planillas',
  'ver_personal',
  'ver_historial',
  'cargar_planillas',
  'ver_perfil_propio',
  'configuracion',
  'ver_informes',
  'gestionar_roles_guardia',
  'crear_bombero',
] as const;

export type AccionPermiso = (typeof ACCIONES_PERMISO)[number];

export const DEFAULTS_POR_NIVEL: Record<number, Record<AccionPermiso, boolean>> = {
  5: {
    ver_todo: true,
    editar_planillas: true,
    eliminar_planillas: true,
    ver_personal: true,
    ver_historial: true,
    cargar_planillas: true,
    ver_perfil_propio: true,
    configuracion: true,
    ver_informes: true,
    gestionar_roles_guardia: true,
    crear_bombero: true,
  },
  4: {
    ver_todo: true,
    editar_planillas: true,
    eliminar_planillas: true,
    ver_personal: true,
    ver_historial: true,
    cargar_planillas: true,
    ver_perfil_propio: true,
    configuracion: false,
    ver_informes: true,
    gestionar_roles_guardia: true,
    crear_bombero: true,
  },
  3: {
    ver_todo: true,
    editar_planillas: false,
    eliminar_planillas: false,
    ver_personal: true,
    ver_historial: true,
    cargar_planillas: true,
    ver_perfil_propio: true,
    configuracion: false,
    ver_informes: false,
    gestionar_roles_guardia: false,
    crear_bombero: false,
  },
  2: {
    ver_todo: true,
    editar_planillas: false,
    eliminar_planillas: false,
    ver_personal: true,
    ver_historial: true,
    cargar_planillas: true,
    ver_perfil_propio: true,
    configuracion: false,
    ver_informes: false,
    gestionar_roles_guardia: false,
    crear_bombero: false,
  },
  1: {
    ver_todo: false,
    editar_planillas: false,
    eliminar_planillas: false,
    ver_personal: false,
    ver_historial: false,
    cargar_planillas: false,
    ver_perfil_propio: true,
    configuracion: false,
    ver_informes: false,
    gestionar_roles_guardia: false,
    crear_bombero: false,
  },
};
